return {
	--成长基金
	"MSG_Welfare.ResGrowthFind",
	"MSG_Welfare.ResActiveGrowthResult",
	"MSG_Welfare.ResGetGrowthRewardResult",
	--转职系统
	"MSG_Player.ResChangeJobResult",
	--离线挂机
	"MSG_Hook.ResHookSetInfo",
	"MSG_Hook.ResOfflineHookResult",
	--造化系统
	"MSG_Nature.ResNatureInfo",
	"MSG_Nature.ResNatureUpLevel",
	"MSG_Nature.ResNatureDrug",
	"MSG_Nature.ResNatureModelSet",
	"MSG_Nature.ResNatureFashionUpLevel",
	"MSG_Nature.ResNatureMountBaseLevel",
	-- 日常
	"MSG_Dailyactive.ResGetActiveReward",
	"MSG_Dailyactive.ResDailyActivePenel",
	"MSG_Dailyactive.ResDailyPushResult",
	--装备强化
	"MSG_Equip.ResEquipStrength",
	"MSG_Equip.ResEquipStrengthUpLevel",
	--天书
	"MSG_GodBook.ResBookInfo",
	"MSG_GodBook.ResGetReward",
	--勇者之颠
	"MSG_zone.ResBravePeakRecord",
	"MSG_zone.ResBravePeakSuccessOneFloorNotice",
	"MSG_zone.ResBravePeakResultPanl",
	--副本剩余时间
	"MSG_copyMap.ResCopymapNeedTime",
	--圣战之启
	"MSG_copyMap.ResTeamCampWar",
	"MSG_copyMap.ResTeamCampWarRank",
	"MSG_copyMap.ResTeamCampWarEndInfo",
	-- 宗派技能
	"MSG_Guild.ResGuildPlayerLearnSkills",
	--宝石
	"MSG_Gem.ResGemInfo",
	"MSG_Gem.ResInlay",
	"MSG_Gem.ResQuickRefineGem",
	"MSG_Gem.ResAutoRefineGem",
	--排行榜
	"MSG_RankList.ResRankInfo",
	"MSG_RankList.ResRankPlayerImageInfo",
	"MSG_RankList.ResWorship",
	"MSG_RankList.ResRankRedPointTip",
	"MSG_RankList.ResRankCompareData",
	--帮会福地称号排行榜
	"MSG_GuildActivity.ResOpenRankPanel",
	--副本系统
	"MSG_copyMap.ResOpenPanel",
	"MSG_copyMap.ResCloneStateChange",
	"MSG_copyMap.ResSingleCloneStateChange",
	--挑战副本
	"MSG_copyMap.ResChallengeInfo",
	"MSG_copyMap.ResChallengeEndInfo",
	"MSG_copyMap.ResChallengeEnterPanel",
	--星级副本
	"MSG_copyMap.ResOpenStarPanel",
	"MSG_copyMap.ResStartCopyInfo",
	"MSG_copyMap.ResStartCopyResult",
	--个人BOSS，
	"MSG_Boss.ResMySelfBossRemainTime",
	"MSG_Boss.ResMySelfBossCopyInfo",
	"MSG_Boss.ResMySelfBossStage",
	"MSG_Boss.ResMySelfBossItemInfo",
	--识海
	"MSG_ShiHai.ResShiHaiData",
	--境界
	"MSG_StateVip.ResGetReward",
	"MSG_StateVip.ResStateVip",
	"MSG_StateVip.ResStateVipBroadcast",
	"MSG_StateVip.ResStateVipRedPoint",
	"MSG_StateVip.ResStateVipGiftList",
	"MSG_StateVip.ResDelStateVipGift",
	"MSG_StateVip.ResStateVipGift",
	--世界BOSS
	"MSG_Boss.ResOpenDreamBoss",
	"MSG_Boss.ResBossKilledInfo",
	"MSG_Boss.ResFollowBoss",
	"MSG_Boss.ResBossRefreshInfo",
	"MSG_Boss.ResBossRefreshTip",
	"MSG_Boss.ResSynHarmRank",
	--竞技场
	"MSG_JJC.ResOpenJJCresult",
	"MSG_JJC.ResUpdateChance",
	"MSG_JJC.ResUpdatePlayers",
	"MSG_JJC.ResYesterdayRank",
	"MSG_JJC.ResReports",
	"MSG_JJC.ResJJCTargetID",
	"MSG_JJC.ResJJCBattleReport",
	"MSG_JJC.ResOnlineJJCInfo",
	"MSG_JJC.ResStartBattleRes",
	--红包
	"MSG_redpacket.ResRedpacketList",
	"MSG_redpacket.ResGetRedPacketInfo",
    "MSG_redpacket.ResClickRedpacket",
    "MSG_redpacket.ResSendRedPacket",
    "MSG_redpacket.ResNewRedPacket",
    "MSG_redpacket.ResMineHaveRedpacket",
	"MSG_redpacket.ResSendMineRechargeRedpacket",
	--成就
	"MSG_Achievement.ResAchievementInfo",
	"MSG_Achievement.ResUpdateAchivement",
	"MSG_Achievement.ResGetAchievement",
	}